### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by mattbasta** [AlmostBetterNetwork/podmaster-host#41]
- [x] Analytics app
- [x] Accounts app
- [x] Dashboard app
- [x] Feedback app
- [x] Podcasts app
- [x] Category selector
- [ ] Podcast import front end
- [ ] Uploader front end
- [x] Network templates
- [x] Feedback templates
- [x] Episode templates
- [x] Podcast templates
- [x] Signup templates
- [x] Player template

**Comment by kimshako** [comment]
@mattbasta Is it possible to contribute for new language? (e.g. Korean)

**Comment by mattbasta** [comment]
@kimshako Everything is ready for translation, but we don't currently have the resources to dedicate to building a translation pipeline and keeping the strings in the app up to date. We plan to prioritize this in the coming year, so stay tuned.

**Comment by kimshako** [comment]
@mattbasta Great! If you need Korean translation, Just let me know. I’m iOS deceloper and my native language is Korean.
